### ISSUE TITLE
示例 footer example 图片无法访问

### ISSUE THREAD

**Issue by Yer11214** [beta4x/vue-copyright-icp-footer#1]
<img width="268" alt="image" src="https://github.com/user-attachments/assets/a519a440-3130-4d96-b6d1-a3586f23237b">

**Comment by beta4x** [comment]
感谢反馈。  
应该是没有科学上网。示例图片就放在该仓库下的 `public/img/footer-example.png`，我看怎么优化下。  

Update：  
1. 测试了下，好像是这样的：如果没科学上网，GitHub 仓库里的图片就无法直接展示，比如可以拿这个链接测试 https://github.com/beta4x/vue-copyright-icp-footer/blob/main/public/img/footer-example.png 。  
2. 修改了下 `README.md` 文件，增加了一些说明及需要科学上网的提示。
